name: Run tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.55.0
          default: true
          components: rustfmt, clippy
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: lint with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --all-targets --
            -W clippy::wildcard_imports
            -W clippy::redundant_closure_for_method_calls
            -W clippy::enum_glob_use
            -A clippy::float_cmp
            -D clippy::unused_io_amount
            -W future_incompatible
            -W nonstandard_style
            -W rust_2018_compatibility
            -W rust_2021_compatibility
            -W unused
      - name: Run Rust tests
        run: cargo test --release
