name: Run tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  # Write permissions are required in order to produce annotations.
  checks: write

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - "1.56.0"
          - "1.62.0"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          default: true
          components: rustfmt, clippy
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Check Rust formatting
        run: cargo fmt -- --check
      - name: lint with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: |
            --all-targets --all-features --
            -D clippy::perf
            -D clippy::wildcard_imports
            -D clippy::redundant_closure_for_method_calls
            -D clippy::enum_glob_use
            -A clippy::float_cmp
            -F clippy::unused_io_amount
            -W future_incompatible
            -D nonstandard_style
            -D rust_2018_compatibility
            -D rust_2021_compatibility
            -D unused
      - name: Run Rust tests
        run: cargo test --release
      - name: Run Rust tests without parallelism
        run: cargo test --release --no-default-features
